create table public.admin (
  id uuid not null default gen_random_uuid (),
  email text not null,
  first_name text not null,
  last_name text not null,
  status text null default 'active'::text,
  approved_by uuid null,
  approved_at timestamp with time zone null,
  rejected_by uuid null,
  rejected_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint admin_pkey primary key (id),
  constraint admin_email_key unique (email)
) TABLESPACE pg_default;

create index IF not exists idx_admin_email on public.admin using btree (email) TABLESPACE pg_default;

create index IF not exists idx_admin_status on public.admin using btree (status) TABLESPACE pg_default;



create table public.allowed_terms (
  id uuid not null default gen_random_uuid (),
  academic_year text not null,
  semester text not null,
  start_date date not null,
  end_date date not null,
  created_at timestamp with time zone not null default now(),
  constraint allowed_terms_pkey primary key (id)
) TABLESPACE pg_default;



create table public.attendance (
  id bigint generated by default as identity not null,
  session_id bigint not null,
  student_id bigint not null,
  status text not null,
  time_in timestamp with time zone null,
  time_out timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint attendance_pkey primary key (id),
  constraint attendance_session_id_student_id_key unique (session_id, student_id),
  constraint attendance_session_id_fkey foreign KEY (session_id) references sessions (id) on delete CASCADE,
  constraint attendance_student_id_fkey foreign KEY (student_id) references students (id) on delete CASCADE,
  constraint attendance_status_check check (
    (
      status = any (
        array[
          'present'::text,
          'absent'::text,
          'late'::text,
          'excused'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_attendance_session_id on public.attendance using btree (session_id) TABLESPACE pg_default;

create index IF not exists idx_attendance_student_id on public.attendance using btree (student_id) TABLESPACE pg_default;

create trigger update_attendance_updated_at BEFORE
update on attendance for EACH row
execute FUNCTION update_updated_at_column ();




create table public.excuse_applications (
  id bigserial not null,
  student_id bigint null,
  session_id bigint null,
  absence_date date not null,
  documentation_url text null,
  status text null default 'pending'::text,
  reviewed_by text null,
  reviewed_at timestamp without time zone null,
  review_notes text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint excuse_applications_pkey primary key (id),
  constraint excuse_applications_session_id_fkey foreign KEY (session_id) references sessions (id),
  constraint excuse_applications_student_id_fkey foreign KEY (student_id) references students (id),
  constraint excuse_applications_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'approved'::text,
          'rejected'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;



create table public.global_trained_models (
  id bigint generated by default as identity not null,
  model_path text not null,
  s3_key text null,
  model_uuid text not null,
  status text not null default 'training'::text,
  sample_count integer not null default 0,
  genuine_count integer not null default 0,
  student_count integer not null default 0,
  training_date timestamp with time zone null default now(),
  accuracy numeric(5, 4) null,
  training_metrics jsonb null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  version integer null default 1,
  parent_model_id bigint null,
  is_active boolean null default true,
  version_notes text null,
  performance_metrics jsonb null,
  far numeric(5, 4) null,
  frr numeric(5, 4) null,
  centroids_path text null,
  mappings_path text null,
  embedding_spec_path text null,
  constraint global_trained_models_pkey primary key (id),
  constraint global_trained_models_status_check check (
    (
      status = any (
        array[
          'training'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_global_trained_models_status on public.global_trained_models using btree (status) TABLESPACE pg_default;

create index IF not exists idx_global_trained_models_active on public.global_trained_models using btree (is_active) TABLESPACE pg_default
where
  (is_active = true);

create index IF not exists idx_global_trained_models_created_at on public.global_trained_models using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_global_trained_models_model_uuid on public.global_trained_models using btree (model_uuid) TABLESPACE pg_default;

create trigger trigger_update_global_model_version
after INSERT
or
update on global_trained_models for EACH row
execute FUNCTION update_global_model_version ();

create trigger update_global_trained_models_updated_at BEFORE
update on global_trained_models for EACH row
execute FUNCTION update_global_trained_models_updated_at ();



create table public.sessions (
  id bigint generated by default as identity not null,
  title text not null,
  program text not null,
  year text not null,
  section text not null,
  date date not null,
  time_in text null,
  time_out text null,
  type text not null default 'class'::text,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  created_by_user_id uuid null,
  status text not null default 'not completed'::text,
  constraint sessions_pkey primary key (id),
  constraint sessions_created_by_user_id_check check (
    (
      (created_by_user_id is null)
      or check_account_exists (created_by_user_id)
    )
  ),
  constraint sessions_status_check check (
    (
      status = any (array['not completed'::text, 'completed'::text])
    )
  ),
  constraint sessions_type_check check (
    (
      type = any (
        array['class'::text, 'event'::text, 'other'::text]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_sessions_program_year_section on public.sessions using btree (program, year, section) TABLESPACE pg_default;

create trigger update_sessions_updated_at BEFORE
update on sessions for EACH row
execute FUNCTION update_updated_at_column ();



create table public.student_signatures (
  id bigint generated always as identity not null,
  student_id bigint not null,
  label text not null,
  s3_key text not null,
  s3_url text not null,
  created_at timestamp with time zone null default now(),
  content_hash text null,
  constraint student_signatures_pkey primary key (id),
  constraint student_signatures_content_hash_key unique (content_hash),
  constraint student_signatures_student_id_fkey foreign KEY (student_id) references students (id) on delete CASCADE,
  constraint student_signatures_label_check check ((label = 'genuine'::text))
) TABLESPACE pg_default;

create index IF not exists idx_student_signatures_hash on public.student_signatures using btree (content_hash) TABLESPACE pg_default;

create index IF not exists idx_student_signatures_student_id on public.student_signatures using btree (student_id) TABLESPACE pg_default;



create table public.students (
  id bigint generated by default as identity not null,
  student_id text not null,
  firstname text not null,
  middlename text null,
  surname text not null,
  program text not null,
  year text not null,
  section text not null,
  sex text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint students_pkey primary key (id),
  constraint students_student_id_key unique (student_id)
) TABLESPACE pg_default;

create index IF not exists idx_students_program_year_section on public.students using btree (program, year, section) TABLESPACE pg_default;

create trigger update_students_updated_at BEFORE
update on students for EACH row
execute FUNCTION update_updated_at_column ();



create table public.trained_models (
  id bigint generated by default as identity not null,
  student_id bigint not null,
  accuracy numeric(5, 4) null,
  training_date timestamp with time zone null default now(),
  status text not null default 'training'::text,
  sample_count integer not null default 0,
  genuine_count integer not null default 0,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  prototype_centroid jsonb null,
  prototype_threshold double precision null,
  embedding_model_path text null,
  version integer null default 1,
  parent_model_id bigint null,
  is_active boolean null default true,
  version_notes text null,
  performance_metrics jsonb null,
  far numeric(5, 4) null,
  frr numeric(5, 4) null,
  global_model_id integer null,
  s3_key text null,
  embedding_s3_key text null,
  model_uuid text null,
  model_path text not null,
  training_metrics jsonb null,
  constraint trained_models_pkey primary key (id),
  constraint trained_models_global_model_id_fkey foreign KEY (global_model_id) references global_trained_models (id) on delete set null,
  constraint trained_models_student_id_fkey foreign KEY (student_id) references students (id) on delete CASCADE,
  constraint trained_models_status_check check (
    (
      status = any (
        array[
          'training'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_trained_models_student_version on public.trained_models using btree (student_id, version) TABLESPACE pg_default;

create index IF not exists idx_trained_models_active on public.trained_models using btree (student_id, is_active) TABLESPACE pg_default
where
  (is_active = true);

create index IF not exists idx_trained_models_global_model_id on public.trained_models using btree (global_model_id) TABLESPACE pg_default;

create index IF not exists idx_trained_models_student_id on public.trained_models using btree (student_id) TABLESPACE pg_default;

create index IF not exists idx_trained_models_status on public.trained_models using btree (status) TABLESPACE pg_default;

create trigger trigger_update_model_version
after INSERT
or
update on trained_models for EACH row
execute FUNCTION update_model_version ();

create trigger update_trained_models_updated_at BEFORE
update on trained_models for EACH row
execute FUNCTION update_updated_at_column ();



create table public.attendance_checker (
  id uuid not null default gen_random_uuid (),
  email text not null,
  first_name text not null,
  last_name text not null,
  admin_id uuid null,
  status text null default 'active'::text,
  approved_by uuid null,
  approved_at timestamp with time zone null,
  rejected_by uuid null,
  rejected_at timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint attendance_checker_pkey primary key (id),
  constraint attendance_checker_email_key unique (email),
  constraint attendance_checker_admin_id_fkey foreign key (admin_id) references admin (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_attendance_checker_email on public.attendance_checker using btree (email) TABLESPACE pg_default;

create index IF not exists idx_attendance_checker_admin_id on public.attendance_checker using btree (admin_id) TABLESPACE pg_default;

create index IF not exists idx_attendance_checker_status on public.attendance_checker using btree (status) TABLESPACE pg_default;


