#!/usr/bin/env node

/**
 * S3 Setup Script for Signature AI Training
 * 
 * This script helps you configure AWS S3 for model exports.
 * Run this script to set up your environment variables.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupS3() {
  console.log('🚀 Setting up AWS S3 for Signature AI Training\n');
  
  console.log('This script will help you configure AWS S3 for model exports.');
  console.log('You will need:');
  console.log('  - AWS Access Key ID');
  console.log('  - AWS Secret Access Key');
  console.log('  - AWS Region (default: us-east-1)');
  console.log('  - S3 Bucket Name (default: signatureai-uploads)\n');
  
  const awsAccessKeyId = await question('Enter your AWS Access Key ID: ');
  const awsSecretAccessKey = await question('Enter your AWS Secret Access Key: ');
  const awsRegion = await question('Enter your AWS Region (default: us-east-1): ') || 'us-east-1';
  const s3Bucket = await question('Enter your S3 Bucket Name (default: signatureai-uploads): ') || 'signatureai-uploads';
  
  const envContent = `# AWS S3 Configuration for AI Models
# Generated by setup-s3.js

# AWS Credentials (Required for S3 uploads)
NEXT_PUBLIC_AWS_ACCESS_KEY_ID=${awsAccessKeyId}
NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY=${awsSecretAccessKey}
NEXT_PUBLIC_AWS_REGION=${awsRegion}
NEXT_PUBLIC_S3_BUCKET=${s3Bucket}

# AI Service Configuration
VITE_AI_BASE_URL=http://localhost:8000

# Enable S3 Storage (set to 'true' to enable S3 exports, 'false' for local downloads only)
VITE_ENABLE_S3_STORAGE=true
`;

  const envPath = path.join(__dirname, '.env');
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Environment file created successfully!');
    console.log(`📁 Location: ${envPath}`);
    console.log('\n🔄 Please restart your development server for changes to take effect.');
    console.log('\n📋 Next steps:');
    console.log('  1. Make sure your S3 bucket exists and has proper permissions');
    console.log('  2. Restart your development server (npm run dev)');
    console.log('  3. Try exporting a model to S3');
  } catch (error) {
    console.error('\n❌ Error creating environment file:', error.message);
  }
  
  rl.close();
}

// Check if .env already exists
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists.');
  question('Do you want to overwrite it? (y/N): ').then((answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      setupS3();
    } else {
      console.log('Setup cancelled.');
      rl.close();
    }
  });
} else {
  setupS3();
}